# About
- Date: 27/09/2022
- Pages: 63

In [1]:
from mxnet import np
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 3, 54, 1], [2, 4,1, 1]])

## Exercise 1
The tensor we got is of `boolean` type with the same size as X and Y

In [2]:
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [3]:
Y

array([[ 2.,  1.,  4.,  3.],
       [ 1.,  3., 54.,  1.],
       [ 2.,  4.,  1.,  1.]])

In [4]:
X > Y

array([[False, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [5]:
X < Y

array([[ True, False,  True, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [6]:
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

## Exercise 2 
- Broadcasting: Do element-wise binary operations even when shapes **differ**. 
	- Requirement: a `1 x n` tensors with a `m x 1` tensors
	- What it do: It copy the 1 row (or column) into the desired shape `m x n` and do the normal element-wise operation.
	- Generalization for multidimensional tensors: `a_1 x a_2 x ... x a_n` with `b_1 x b_2 x ... x b_m`.
		- Requirement: `a_i == 1` or `b_i == 1` for every `i`.
		- Works like the 2 dimensional case.

In [7]:
X = np.arange(6).reshape(1, 6, 1)
Y = np.arange(15).reshape(3, 1, 5)

In [8]:
X

array([[[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]]])

In [9]:
Y

array([[[ 0.,  1.,  2.,  3.,  4.]],

       [[ 5.,  6.,  7.,  8.,  9.]],

       [[10., 11., 12., 13., 14.]]])

In [10]:
T = X + Y
print(T.shape)
T

(3, 6, 5)


array([[[ 0.,  1.,  2.,  3.,  4.],
        [ 1.,  2.,  3.,  4.,  5.],
        [ 2.,  3.,  4.,  5.,  6.],
        [ 3.,  4.,  5.,  6.,  7.],
        [ 4.,  5.,  6.,  7.,  8.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 5.,  6.,  7.,  8.,  9.],
        [ 6.,  7.,  8.,  9., 10.],
        [ 7.,  8.,  9., 10., 11.],
        [ 8.,  9., 10., 11., 12.],
        [ 9., 10., 11., 12., 13.],
        [10., 11., 12., 13., 14.]],

       [[10., 11., 12., 13., 14.],
        [11., 12., 13., 14., 15.],
        [12., 13., 14., 15., 16.],
        [13., 14., 15., 16., 17.],
        [14., 15., 16., 17., 18.],
        [15., 16., 17., 18., 19.]]])